services:
 wayfair:
  container_name: wayfair
  env_file: ./.env
  build:
      context: .
      dockerfile: Dockerfile
  restart: unless-stopped
  volumes:
    - ./db.sqlite3:/application/db.sqlite3
  ports:
   - "8000:8000"
  networks:
   - wayfair

networks:
  wayfair:
