# Generated by Django 5.2.7 on 2025-10-15 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField(help_text='Айди процесса', verbose_name='Айди процесса')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('status', models.BooleanField(default=True, help_text='Активность')),
            ],
            options={
                'verbose_name': 'Процесс',
                'verbose_name_plural': 'Процесс',
                'db_table': 'process',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='Токен вэйфэир')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'token',
                'verbose_name_plural': 'token',
                'db_table': 'token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='Уникальный идентификатор TG', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('process', models.OneToOneField(blank=True, help_text='Токен пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_for_process', to='wayfair_bot.process', verbose_name='Токен')),
                ('tg_token', models.OneToOneField(blank=True, help_text='Токен пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to='wayfair_bot.token', verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'db_table': 'user',
                'ordering': ['-created_at'],
            },
        ),
    ]
