# Generated by Django 5.2.7 on 2025-10-16 06:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfair_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(blank=True, default=0, help_text='Уникальный идентификатор TG', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='Accept',
            field=models.TextField(blank=True, default='application/json', help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='Accept_Encoding',
            field=models.TextField(blank=True, default='gzip, deflate, br', help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='Accept_Language',
            field=models.TextField(blank=True, default='ru', help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='AppAuthEnabled',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='Connection',
            field=models.TextField(blank=True, default='keep-alive', help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='Content_Type',
            field=models.TextField(blank=True, default='application/json', help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='Cookie',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='Host',
            field=models.TextField(blank=True, default='www.wayfair.com', help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='User_Agent',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='X_Graph_Type',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='X_PX_AUTHORIZATION',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='X_PX_DEVICE_FP',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='X_PX_DEVICE_MODEL',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='X_PX_HELLO',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='X_PX_MOBILE_SDK_VERSION',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='X_PX_OS',
            field=models.TextField(blank=True, default='iOS', help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='X_PX_OS_VERSION',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='X_PX_UUID',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='X_PX_VID',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='wf_customer_guid',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='wf_device_guid',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='wf_locale',
            field=models.TextField(blank=True, default='en-US', help_text='Токен вэйфэир', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='wf_pageview_id',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.TextField(blank=True, default=None, help_text='Токен вэйфэир', null=True),
        ),
    ]
