# Generated by Django 5.2.7 on 2025-10-15 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfair_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='pc_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokoken', to='wayfair_bot.token', verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.BooleanField(default=True, help_text='Активность'),
        ),
    ]
