# Generated by Django 5.2.7 on 2025-10-17 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfair_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ', primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(blank=True, default=0, help_text='Уникальный идентификатор TG', null=True)),
            ],
        ),
    ]
