# Generated by Django 5.2.7 on 2025-10-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayfair_bot', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
